changesetBaseRefs:
  - HEAD
  - master
  - main
  - origin/master
  - origin/main
  - upstream/master
  - upstream/main

compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

yarnPath: .yarn/releases/yarn-4.2.2.cjs
