changesetBaseRefs:
  - HEAD
  - master
  - main
  - origin/master
  - origin/main
  - upstream/master
  - upstream/main

compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnpm

yarnPath: .yarn/releases/yarn-4.4.0.cjs
