name: Compilation & Unit Tests
on:
    push:
        branches: ["*"]
    pull_request:
jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout
            - uses: actions/setup-node
              with:
                  node-version: 21
            - run: yarn
            - run: yarn build
            - run: yarn test
