name: Compilation & Unit Tests
on:
  push:
    branches: ["*"]
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: "pnpm"

      - run: corepack enable
      - run: corepack prepare pnpm@latest --activate

      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm test
